Repository Team-BBANGZIP/BBANGZIP-SERVER, pull requests merged in 2025-09, with the labels that each got.

#41 :sparkles: [feat] #39 SpringSecurity + JWT 및 Token 도메인 구현
  bbangzip-api/build.gradle
  bbangzip-api/src/main/java/org/sopt/config/SecurityConfig.java
  bbangzip-api/src/main/java/org/sopt/test/controller/JwtController.java
  bbangzip-api/src/main/java/org/sopt/test/dto/jwt/IssueTokenRequest.java
  bbangzip-api/src/main/java/org/sopt/test/dto/jwt/JwtTokensDto.java
  bbangzip-api/src/main/java/org/sopt/test/dto/jwt/TestDto.java
  bbangzip-api/src/main/java/org/sopt/test/dto/jwt/TestSecurity.java
  bbangzip-api/src/main/java/org/sopt/user/controller/UserController.java
  bbangzip-auth/build.gradle
  bbangzip-auth/src/main/java/org/sopt/exception/AuthBaseException.java
  bbangzip-auth/src/main/java/org/sopt/exception/AuthErrorCode.java
  bbangzip-auth/src/main/java/org/sopt/exception/BusinessException.java
  bbangzip-auth/src/main/java/org/sopt/exception/InvalidAuthHeaderException.java
  bbangzip-auth/src/main/java/org/sopt/exception/InvalidSecretKeyException.java
  bbangzip-auth/src/main/java/org/sopt/exception/InvalidTokenException.java
  bbangzip-auth/src/main/java/org/sopt/exception/TokenHashingException.java
  bbangzip-auth/src/main/java/org/sopt/exception/TokenNotFoundException.java
  bbangzip-auth/src/main/java/org/sopt/exception/UnAuthorizedException.java
  bbangzip-auth/src/main/java/org/sopt/jwt/annotation/UserId.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/authentication/UserAuthentication.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/authentication/UserAuthenticationFactory.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/authentication/UserRole.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/domain/Token.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/domain/TokenRepository.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/domain/type/AuthProvider.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/domain/type/DeviceType.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/web/ExceptionHandlerFilter.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/web/JwtAuthenticationEntryPoint.java
  bbangzip-auth/src/main/java/org/sopt/jwt/auth/web/JwtAuthenticationFilter.java
  bbangzip-auth/src/main/java/org/sopt/jwt/core/JwtClaimsKeys.java
  bbangzip-auth/src/main/java/org/sopt/jwt/core/JwtTokenProvider.java
  bbangzip-auth/src/main/java/org/sopt/jwt/core/TokenHasher.java
  bbangzip-auth/src/main/java/org/sopt/jwt/core/TokenId.java
  bbangzip-auth/src/main/java/org/sopt/jwt/support/AuthConstants.java
  bbangzip-auth/src/main/java/org/sopt/jwt/support/SecurityUtils.java
  bbangzip-auth/src/main/java/org/sopt/jwt/support/logsupport/ErrorLogger.java
  bbangzip-auth/src/main/java/org/sopt/jwt/support/logsupport/ErrorResponder.java
  bbangzip-domain/build.gradle
  bbangzip-domain/src/main/java/org/sopt/user/domain/UserEntity.java
  bbangzip-domain/src/main/java/org/sopt/user/domain/UserTableConstants.java
Labels: 영주🐣, feat ✨

#42 :sparkles: [feat] #39 해당 번호 이슈 관련해서 예외 핸들링 커밋 빠진 것 추가
  bbangzip-api/src/main/java/org/sopt/common/GlobalExceptionHandler.java
Labels: 영주🐣, feat ✨

#47 :sparkles: [chore] #46 Controller 에 @UserId 주입받도록 수정
  bbangzip-api/src/main/java/org/sopt/category/controller/CategoryController.java
  bbangzip-api/src/main/java/org/sopt/todo/controller/TodoController.java
Labels: 영주🐣, chore🔧

#52 ✏️ [fix] #49 카테고리 수정 시 공백/동일값 처리 오류 수정
  bbangzip-api/src/main/java/org/sopt/category/dto/req/CategoryUpdateReq.java
  bbangzip-domain/src/main/java/org/sopt/category/domain/CategoryEntity.java
Labels: 예은🐇, fix✏️

#60 [feat] #59 타이머 완료 API 구현
  bbangzip-api/src/main/java/org/sopt/auth/service/AuthService.java
  bbangzip-api/src/main/java/org/sopt/timer/controller/TimerController.java
  bbangzip-api/src/main/java/org/sopt/timer/dto/req/TimerDoneReq.java
  bbangzip-api/src/main/java/org/sopt/timer/dto/res/TimerDoneRes.java
  bbangzip-api/src/main/java/org/sopt/timer/service/TimerService.java
  bbangzip-api/src/main/java/org/sopt/token/TokenService.java
  bbangzip-domain/src/main/java/org/sopt/dailybaking/domain/DailyBakingEntity.java
  bbangzip-domain/src/main/java/org/sopt/dailybaking/facade/DailyBakingFacade.java
  bbangzip-domain/src/main/java/org/sopt/dailybaking/facade/DailyBakingRetriever.java
  bbangzip-domain/src/main/java/org/sopt/dailybaking/facade/DailyBakingSaver.java
  bbangzip-domain/src/main/java/org/sopt/dailybaking/repository/DailyBakingRepository.java
  bbangzip-domain/src/main/java/org/sopt/user/domain/UserEntity.java
  bbangzip-domain/src/main/java/org/sopt/user/facade/UserFacade.java
  bbangzip-domain/src/main/java/org/sopt/user/facade/UserUpdater.java
  bbangzip-domain/src/main/java/org/sopt/user/repository/UserRepository.java
Labels: 영주🐣, feat ✨

#58 ✨ [feat] #56 기본 정보 수정 API 구현
  bbangzip-api/src/main/java/org/sopt/user/controller/UserController.java
  bbangzip-api/src/main/java/org/sopt/user/dto/req/UserProfileUpdateReq.java
  bbangzip-api/src/main/java/org/sopt/user/dto/res/UserProfileUpdateRes.java
  bbangzip-api/src/main/java/org/sopt/user/service/UserService.java
  bbangzip-domain/src/main/java/org/sopt/user/domain/UserEntity.java
  bbangzip-domain/src/main/java/org/sopt/user/enums/DefaultProfileImage.java
  bbangzip-domain/src/main/java/org/sopt/user/exception/InvalidProfileImageKeyException.java
  bbangzip-domain/src/main/java/org/sopt/user/exception/UserCoreErrorCode.java
  bbangzip-domain/src/main/java/org/sopt/user/facade/UserFacade.java
  bbangzip-domain/src/main/java/org/sopt/user/facade/UserUpdater.java
Labels: 영주🐣, feat ✨
